# Generated by Django 5.2.1 on 2025-05-12 18:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('settings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=250)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('vat_id', models.CharField(blank=True, max_length=11, null=True)),
                ('street', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.customertype')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='settings.gender')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('canceled', 'Canceled'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('offer_note', models.TextField(blank=True, max_length=1500, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valid_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=18, null=True)),
                ('total_sum', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=18, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), max_digits=5, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='sales.customer')),
                ('products', models.ManyToManyField(blank=True, related_name='offers', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='offers', to='settings.tenant')),
            ],
            options={
                'ordering': ['-date_created', '-offer_number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('canceled', 'Canceled'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='sent', max_length=20)),
                ('invoice_note', models.TextField(blank=True, max_length=1500, null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('valid_to', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=18, null=True)),
                ('total_sum', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=18, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), max_digits=5, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), editable=False, max_digits=5, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='sales.customer')),
                ('products', models.ManyToManyField(blank=True, related_name='invoices', to='products.product')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoices', to='settings.tenant')),
                ('offer', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invoice', to='sales.offer')),
            ],
            options={
                'ordering': ['-date_created', '-invoice_number'],
            },
        ),
    ]
