# Generated by Django 5.2.1 on 2025-05-12 18:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingredient name', max_length=150)),
                ('code', models.CharField(help_text='Ingredient code', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Ingredient description', max_length=150, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.00'), help_text='Ingredient price', max_digits=18, null=True)),
                ('price_mod', models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.00'), help_text='Ingredient price modificator', max_digits=5, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.00'), help_text='Ingredient total price', max_digits=18, null=True)),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=150)),
                ('code', models.CharField(help_text='Product code', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Product description', max_length=150, null=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=6, default=Decimal('0.00'), help_text='Product base price', max_digits=18, null=True)),
                ('price_mod', models.DecimalField(blank=True, decimal_places=3, default=Decimal('1.00'), help_text='Product base price modificator', max_digits=5, null=True)),
                ('fixed_costs', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), help_text='Fixed costs for product production', max_digits=18, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0.00'), help_text='Product total price', max_digits=18, null=True)),
                ('ingredients', models.ManyToManyField(blank=True, related_name='products', to='products.ingredient')),
                ('ingredients_from_products', models.ManyToManyField(blank=True, to='products.product')),
            ],
            options={
                'ordering': ['name', 'code'],
            },
        ),
    ]
